name: Github publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: |
          mvn clean package -DskipTests
          ls -la target/*.jar

      - name: Upload JAR as artifact
        uses: actions/upload-artifact@v3
        with:
          name: jaserreports-arabic-1.0.jar
          path: target/jaserreports-arabic-1.0.jar
