# This workflow will build a package using Maven and then publish it to maven central

name: release-maven-central

on:
  push:
    branches: [master]
  release:
    types: [created]
    

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Import GPG signing key  
      uses: crazy-max/ghaction-import-gpg@v5
      with:
        gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
        passphrase: ${{ secrets.MAVEN_SIGNING_KEY_PASSPHRASE }}
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: 'maven'
        server-id: maven-central-release
        server-username: MVN_CENTRAL_USERNAME
        server-password: MVN_CENTRAL_PASSWORD

    - name: Release to Maven repo
      run: |
          ./mvnw -Dgpg.keyname=${{ secrets.GPG_KEY_NAME }} -Dgpg.passphrase=${{ secrets.MAVEN_SIGNING_KEY_PASSPHRASE }} deploy
      env:
        MVN_CENTRAL_USERNAME: ${{ secrets.MVN_CENTRAL_USERNAME }}
        MVN_CENTRAL_PASSWORD: ${{ secrets.MVN_CENTRAL_PASSWORD }}
